# Generated by Django 5.1.4 on 2024-12-08 07:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
